Repository BIPA-8-3/BIZSurvey_FRONT, pull requests merged in 2023-12, with the labels that each got.

#51 [Design] : 워크스페이스 레이아웃 구현
  src/App.js
  src/assets/img/logo-2.png
  src/components/common/BizCard2.jsx
  src/components/workspace/ButtonItem.jsx
  src/components/workspace/DefaultCard.jsx
  src/components/workspace/Item.jsx
  src/components/workspace/NavBar.jsx
  src/components/workspace/SurveyCard.jsx
  src/components/workspace/WorkspaceHeader.jsx
  src/index.js
  src/pages/Layout.jsx
  src/pages/workspace/Main.jsx
  src/routes/Router.js
  src/style/Common.css
  src/style/workspace/ButtonItem.module.css
  src/style/workspace/DefaultCard.module.css
  src/style/workspace/Item.module.css
  src/style/workspace/Main.module.css
  src/style/workspace/Navbar.module.css
  src/style/workspace/SurveyCard.module.css
  src/style/workspace/WorkspaceHeader.module.css
Labels: enhancement

#69 [Feat] : Add CommunityPost Component Functions
  src/App.js
  src/components/admin/ClaimModal.jsx
  src/components/admin/ReportedClaimList.jsx
  src/components/community/CommunityPost.jsx
  src/components/community/CommunityTable.jsx
  src/components/surveyCommunity/SurveyListModal.jsx
Labels: enhancement

#70 [Refactor] : Add CommunityTable Functions
  src/components/community/CommunityTable.jsx
  src/components/surveyCommunity/SurveyListModal.jsx
  src/style/community/Table.module.css
Labels: enhancement

#79 [Feat] : SurveyPostContainer 무한 스크롤 추가
  package-lock.json
  package.json
  src/components/common/SurveyCard.jsx
  src/components/common/SurveyPostContainer.jsx
  src/components/community/Comment.jsx
  src/components/community/CommunityDetail.jsx
  src/components/community/CommunityTable.jsx
  src/components/community/ParentsComment.jsx
  src/components/community/VoteWrite.jsx
Labels: enhancement

#89 [Feat] : add search service
  src/components/common/Search.jsx
  src/components/common/SearchResult.jsx
  src/components/common/SearchResultTable.jsx
  src/components/common/SurveyCard.jsx
  src/components/common/SurveyPostContainer.jsx
  src/components/community/ChildComment.jsx
  src/components/community/CommunityDetail.jsx
  src/components/community/CommunityPost.jsx
  src/components/community/ParentsComment.jsx
  src/components/surveyCommunity/SurveyCommunityDetail.jsx
  src/routes/Router.js
Labels: enhancement

#93 [Feat] : Add Community Write Service
  src/components/community/CommunityWrite.jsx
  src/components/community/RegisterVote.jsx
Labels: enhancement

#115 [Feat] : 점수 설문 워크스페이스 연동 & 공유 페이지 구현
  src/pages/survey/CreateScoreSurveyPage.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/SharedSurvey.jsx
  src/style/workspace/SharedFooter.module.css
  src/style/workspace/SharedSurvey.module.css
Labels: enhancement

#124 [Feat] : 설문지 외부 공유 & 기본형 설문지 참가 및 통계 구현
  src/components/survey/surveyInfo/resultTab/PersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/PostResult.jsx
  src/components/survey/surveyInfo/resultTab/ResultView.jsx
  src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx
  src/components/survey/surveyInfo/resultTab/UserList.jsx
  src/components/surveyCommunity/CommunitySurveyWrite.jsx
  src/pages/workspace/SharedSurvey.jsx
  src/pages/workspace/api.js
  src/style/workspace/WorkspaceHeader.module.css
Labels: enhancement

#130 [Feat] : 외부 공유 통계 구현
  src/components/survey/surveyInfo/resultTab/PostResult.jsx
  src/components/survey/surveyInfo/resultTab/ResultView.jsx
  src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/api.js
Labels: enhancement

#132 [Feat : add Claim service]
  src/components/common/ClaimReasonModal.jsx
  src/components/community/CommunityDetail.jsx
  src/components/community/ParentsComment.jsx
  src/components/surveyCommunity/SurveyCommunityDetail.jsx
  src/components/surveyCommunity/SurveyListModal.jsx
Labels: enhancement

#138 [Refactor] : 워크스페이스의 설문지 기능 별도 페이지로 분리 및 관리자 이미지 불러오기 구현
  src/components/common/SurveyPostContainer.jsx
  src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx
  src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx
  src/components/workspace/ManagementModal.jsx
  src/components/workspace/MoreMenu.jsx
  src/components/workspace/Navbar.jsx
  src/components/workspace/ProfileContainer.jsx
  src/components/workspace/ShareModal.jsx
  src/components/workspace/SurveyCard.jsx
  src/components/workspace/SurveyCreateModal.jsx
  src/components/workspace/WorkspaceModal.jsx
  src/pages/Layout.jsx
  src/pages/survey/CreateSurveyPage.jsx
  src/pages/survey/EditSurveyPage.jsx
  src/pages/survey/SurveyInfoPage.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/WorkspaceContext.js
  src/routes/Router.js
  src/style/survey/CreatePage.module.css
  src/style/survey/EditSurveyPage.module.css
  src/style/workspace/ProfileContainer.module.css
Labels: enhancement

#141 [Feat] : 워크스페이스 접근 권한 추가 & 메모리 제한 설정
  package.json
  src/components/workspace/WorkspaceHeader.jsx
  src/pages/workspace/WorkspaceContext.js
  src/pages/workspace/api.js
Labels: enhancement

#145 [Refactor] : 빌드 메모리 설정 & 관리자 사진 변경
  package.json
  src/components/workspace/ProfileContainer.jsx
  src/pages/workspace/Main.jsx
Labels: enhancement

#147 [Refactor] : 설문 개별 통계 userList 수정
  src/components/survey/surveyInfo/resultTab/PersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/PostResult.jsx
  src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx
  src/components/survey/surveyInfo/resultTab/UserList.jsx
Labels: enhancement

#149 [Refactor] : 권한 수정 및 Navbar Profile 수정
  src/components/workspace/Navbar.jsx
  src/pages/workspace/WorkspaceContext.js
Labels: enhancement

#151 [Refactor] : add surveycard import
  src/components/workspace/SurveyCard.jsx
Labels: enhancement

#152 Dev
  src/components/workspace/SurveyCard.jsx
Labels: enhancement

#153 [Refactor] : CORS 설정
  package.json
  src/components/api/ApiCall.js
  src/components/user/Login.jsx
  src/pages/workspace/api.js
Labels: enhancement

#154 [Feat] : 공통 axios 호출 File 추가
  src/pages/workspace/api.js
Labels: enhancement

#165 [Fix] : 헤더 & 네비 & 점수형 설문지 수정
  src/components/common/SurveyPostContainer.jsx
  src/components/workspace/Navbar.jsx
  src/components/workspace/WorkspaceHeader.jsx
  src/pages/survey/CreateScoreSurveyPage.jsx
  src/pages/survey/EditScoreSurveyPage.jsx
  src/style/workspace/Main.module.css
Labels: enhancement

#166 Dev
  package.json
  src/components/api/ApiCall.js
  src/components/common/SurveyCard.jsx
  src/components/common/SurveyPostContainer.jsx
  src/components/community/CommunityDetail.jsx
  src/components/community/CommunityWrite.jsx
  src/components/community/CreateVote.jsx
  src/components/community/EditCommunityPost.jsx
  src/components/community/RegisterVote.jsx
  src/components/community/VoteResult.jsx
  src/components/community/VoteWrite.jsx
  src/components/survey/surveyForm/QuestionComp.jsx
  src/components/survey/surveyForm/ScoreQuestion.jsx
  src/components/survey/surveyForm/options/ChoiceOption.jsx
  src/components/survey/surveyForm/options/DateOption.jsx
  src/components/survey/surveyForm/options/FileOption.jsx
  src/components/survey/surveyForm/score/ScoreChoiceOption.jsx
  src/components/survey/surveyForm/score/ScoreOptionSelect.jsx
  src/components/survey/surveyInfo/ButtonTab.jsx
  src/components/survey/surveyInfo/ScorePersonalResult.jsx
  src/components/survey/surveyInfo/SurveyTitle.jsx
  src/components/survey/surveyInfo/infoOptions/DateInfo.jsx
  src/components/survey/surveyInfo/infoTab/QuestionInfo.jsx
  src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx
  src/components/survey/surveyInfo/resultTab/PersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/PostResult.jsx
  src/components/survey/surveyInfo/resultTab/ResultView.jsx
  src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/components/survey/surveyInfo/resultTab/SurvePostSelect.jsx
  src/components/survey/surveyInfo/resultTab/UserList.jsx
  src/components/survey/surveyInfo/resultTab/personalOption/ScoreResultOption.jsx
  src/components/survey/surveyInfo/resultTab/totalOptions/FileList.jsx
  src/components/survey/surveyInfo/resultTab/totalOptions/TextList.jsx
  src/components/surveyCommunity/CommunitySurveyWrite.jsx
  src/components/surveyCommunity/SurveyCommunityDetail.jsx
  src/components/surveyCommunity/SurveyCommunityWrite.jsx
  src/components/user/AdditionalJoin.jsx
  src/components/user/ChangePassword.jsx
  src/components/user/EmailValidation.jsx
  src/components/user/Login.jsx
  src/components/user/Mypage.jsx
  src/components/user/MypageHeader.jsx
  src/components/user/MypagePasswordChange.jsx
  src/components/user/MypagePlanDetail.jsx
  src/components/user/MypageUserInfo.jsx
  src/components/user/UserInfoEditForm.jsx
  src/components/workspace/Navbar.jsx
  src/components/workspace/WorkspaceHeader.jsx
  src/pages/admin/AdminLoginPage.jsx
  src/pages/survey/CreateScoreSurveyPage.jsx
  src/pages/survey/CreateSurveyPage.jsx
  src/pages/survey/EditScoreSurveyPage.jsx
  src/pages/survey/EditSurveyPage.jsx
  src/pages/survey/SurveyInfoPage.jsx
  src/pages/survey/SurveyResultPage.jsx
  src/pages/workspace/api.js
  src/routes/Router.js
  src/style/user/MypageHeader.module.css
  src/style/workspace/Main.module.css
Labels: enhancement

#168 [Chore] : 서버 URI 변경
  src/pages/workspace/api.js
Labels: enhancement

#169 Dev
  src/components/community/CommunityWrite.jsx
  src/components/community/EditCommunityPost.jsx
  src/pages/workspace/api.js
Labels: enhancement

#173 [Refactor] : 엑셀, 파일 uri수정 & 통신 공통 메소드 정의 & login 수정
  src/components/api/ApiCall.js
  src/components/survey/surveyInfo/resultTab/PostResult.jsx
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/components/survey/surveyInfo/resultTab/totalOptions/FileList.jsx
  src/components/user/MypagePlanDetail.jsx
  src/pages/survey/EditScoreSurveyPage.jsx
  src/pages/workspace/api.js
Labels: enhancement

#185 [Fix] : 워크스페이스 오류 수정
  src/components/workspace/AdminItem.jsx
  src/components/workspace/Item.jsx
  src/components/workspace/ManagementModal.jsx
  src/components/workspace/MoreMenu.jsx
  src/components/workspace/Navbar.jsx
  src/components/workspace/ProfileContainer.jsx
  src/components/workspace/ShareModal.jsx
  src/components/workspace/SurveyCard.jsx
  src/components/workspace/WorkspaceModal.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/WorkspaceContext.js
  src/style/survey/EditSurveyPage.module.css
  src/style/workspace/AdminItem.module.css
  src/style/workspace/Main.module.css
  src/style/workspace/MoreMenu.module.css
  src/style/workspace/Navbar.module.css
  src/style/workspace/SurveyCard.module.css
Labels: enhancement

#187 [Refactor] : refactor community service
  src/components/community/ChildCommentForm.jsx
  src/components/community/Comment.jsx
  src/components/community/CommunityDetail.jsx
  src/components/community/CommunityWrite.jsx
  src/components/surveyCommunity/SurveyCommunityWrite.jsx
  src/components/surveyCommunity/SurveyListModal.jsx
Labels: bug

#196 [Fixs] : 워크스페이스 오류 수정
  src/components/survey/surveyInfo/infoTab/SurveyInfo.jsx
  src/components/workspace/AdminItem.jsx
  src/components/workspace/ManagementModal.jsx
  src/components/workspace/MoreMenu.jsx
  src/components/workspace/Navbar.jsx
  src/components/workspace/ShareModal.jsx
  src/components/workspace/SurveyCard.jsx
  src/pages/survey/EditSurveyPage.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/WorkspaceContext.js
  src/pages/workspace/api.js
  src/style/survey/EditSurveyPage.module.css
  src/style/workspace/Modal.module.css
Labels: enhancement

#199 [Feat] : 설문 옵션 중복 제거
  src/components/survey/surveyForm/QuestionComp.jsx
  src/components/survey/surveyForm/ScoreQuestion.jsx
  src/components/survey/surveyForm/options/ChoiceOption.jsx
  src/components/survey/surveyForm/score/ScoreChoiceOption.jsx
  src/pages/survey/CreateScoreSurveyPage.jsx
  src/pages/survey/CreateSurveyPage.jsx
  src/pages/survey/EditScoreSurveyPage.jsx
  src/pages/survey/EditSurveyPage.jsx
Labels: enhancement

#200 [Fixs] : 워크스페이스 오류 수정
  src/components/workspace/ShareItem.jsx
  src/components/workspace/ShareModal.jsx
  src/components/workspace/SharedHistoryItem.jsx
  src/pages/survey/SurveyInfoPage.jsx
  src/pages/workspace/Main.jsx
  src/style/workspace/MoreMenu.module.css
  src/style/workspace/ShareItem.module.css
  src/style/workspace/ShareModal.module.css
  src/style/workspace/SharedHistoryItem.module.css
  src/style/workspace/WorkspaceHeader.module.css
Labels: enhancement

#201 [Refactor] : 개별 응답 수정
  src/components/survey/surveyInfo/resultTab/PersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/UserList.jsx
Labels: enhancement

#202 [Refactor] : 비회원 설문 게시글 조회
  src/components/surveyCommunity/SurveyCommunityDetail.jsx
Labels: enhancement

#203 [Feat] : 외부공유 마감날짜 수정기능 추가 & 공유 모달 UI 변경
  src/components/workspace/ShareModal.jsx
  src/components/workspace/SharedHistoryItem.jsx
  src/components/workspace/WorkspaceModal.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/api.js
  src/style/workspace/ShareItem.module.css
  src/style/workspace/ShareModal.module.css
  src/style/workspace/SharedHistoryItem.module.css
Labels: enhancement

#205 [Refactor] : 설문 참여 파일 크기 제한
  src/components/surveyCommunity/survey/FileOption.jsx
  src/components/surveyCommunity/survey/SurveyQuestion.jsx
Labels: enhancement

#206 [Feat] : 공유 양식 초기화 기능 추가 & 설문 폼 CSS 수정
  src/components/surveyCommunity/survey/SurveyForm.jsx
  src/components/surveyCommunity/survey/SurveyQuestion.jsx
  src/components/workspace/SharedFooter.jsx
  src/pages/survey/CreateScoreSurveyPage.jsx
  src/pages/survey/CreateSurveyPage.jsx
  src/pages/survey/EditScoreSurveyPage.jsx
  src/pages/survey/EditSurveyPage.jsx
  src/pages/survey/SurveyInfoPage.jsx
  src/pages/workspace/SharedSurvey.jsx
  src/style/workspace/SharedSurvey.module.css
Labels: enhancement

#207 [Feat] : 양식 지우기 기능
  src/components/common/Plan.jsx
  src/components/common/SCommunitySearchResult.jsx
  src/components/common/SearchResultTable.jsx
  src/components/common/SurveyPostContainer.jsx
  src/components/community/CommunityPost.jsx
  src/components/community/CommunityWrite.jsx
  src/components/community/EditCommunityPost.jsx
  src/components/survey/surveyForm/EditSurveyTitle.jsx
  src/components/surveyCommunity/CommunitySurveyWrite.jsx
  src/components/surveyCommunity/EditSurveyCommunity.jsx
  src/components/surveyCommunity/SurveyCommunityWrite.jsx
  src/components/user/Join.jsx
  src/components/user/Login.jsx
  src/components/user/MypagePlanDetail.jsx
  src/style/surveyCommunity/CommunitySurveyWrite.module.css
Labels: enhancement

#210 [Fix] : 워크스페이스 키 이벤트 & 오류 수정
  src/components/workspace/ManagementModal.jsx
  src/components/workspace/ShareItem.jsx
  src/components/workspace/WorkspaceModal.jsx
  src/pages/workspace/Main.jsx
Labels: enhancement

#214 [Fix] : 설문 정렬 수정
  src/components/survey/surveyForm/options/ChoiceOption.jsx
  src/components/survey/surveyForm/score/ScoreChoiceOption.jsx
  src/components/survey/surveyInfo/resultTab/PersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/pages/survey/CreateScoreSurveyPage.jsx
  src/pages/survey/CreateSurveyPage.jsx
  src/pages/survey/EditScoreSurveyPage.jsx
  src/pages/survey/EditSurveyPage.jsx
Labels: bug, enhancement

#218 [Refacor] : 통합 배포
  package-lock.json
  package.json
  src/components/common/SurveyPostContainer.jsx
  src/components/survey/surveyInfo/resultTab/PersonalResult.jsx
  src/components/survey/surveyInfo/resultTab/ScorePersonalResult.jsx
  src/components/workspace/AdminItem.jsx
  src/components/workspace/Item.jsx
  src/components/workspace/ManagementModal.jsx
  src/components/workspace/MoreMenu.jsx
  src/components/workspace/Navbar.jsx
  src/components/workspace/SSEComponent.jsx
  src/components/workspace/ShareModal.jsx
  src/components/workspace/SharedHistoryItem.jsx
  src/components/workspace/SurveyCard.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/WorkspaceContext.js
  src/pages/workspace/authenticationApi.js
  src/style/workspace/Main.module.css
  src/style/workspace/SharedHistoryItem.module.css
Labels: enhancement

#222 [Fix] : 설문 순서 정렬
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/pages/survey/SurveyInfoPage.jsx
Labels: bug

#223 [Fix] : 설문 순서 정렬
  src/components/common/SCommunitySearch.jsx
  src/components/common/SCommunitySearchResult.jsx
  src/components/common/Search.jsx
  src/components/common/SearchResultTable.jsx
  src/components/community/CommunityWrite.jsx
  src/components/community/ParentsComment.jsx
  src/components/community/VoteWrite.jsx
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/pages/survey/SurveyInfoPage.jsx
Labels: bug

#225 [Fix] : 점수 설문 정렬 수정
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
Labels: bug

#226 [Fix] : 점수 설문 정렬 수정
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/components/user/MypageHeader.jsx
Labels: bug

#227 [Fix] : 설문 순서 정렬
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
Labels: bug

#228 [Comment] : 주석제거
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/pages/survey/SurveyInfoPage.jsx
Labels: enhancement

#229 [Comment] : 콘솔 제거
  src/components/survey/surveyInfo/resultTab/ScorePostResult.jsx
  src/pages/survey/SurveyInfoPage.jsx
Labels: enhancement

#230 [Refactor] : SSE 제거, console 제거
  src/components/workspace/Navbar.jsx
  src/components/workspace/SSEComponent.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/WorkspaceContext.js
Labels: enhancement

#231 [Refactor] : SSE 제거, console 제거
  src/components/workspace/Navbar.jsx
  src/components/workspace/SSEComponent.jsx
  src/pages/workspace/Main.jsx
  src/pages/workspace/WorkspaceContext.js
Labels: enhancement

#232 [Refactor] : 공유 메일 에러 메세지 수정
  src/pages/workspace/Authorization.jsx
Labels: enhancement

#233 [Refactor] : 공유 메일 에러 메세지 수정
  src/pages/workspace/Authorization.jsx
Labels: enhancement
